In [2]:
from random import randint
import numpy as np

n, m = 50, 50
min_limit = -250
max_limit = 1007

a = [[randint(min_limit, max_limit) for j in range(m)] for i in range(n)]
an = np.asarray(a)
print(an)

[[ 962  442 -178 ... -209  702  860]
 [ 811  211  567 ...  920   32  626]
 [ 679 -249  884 ...  213  993  609]
 ...
 [ 117 -127  330 ...  315  313  512]
 [ 564  806 -102 ...   16  806 1005]
 [ 263  120  -19 ...   50  885   19]]


In [3]:
%%time
import numpy as np

def heap_sort(alist):
    build_max_heap(alist)
    for i in range(len(alist) - 1, 0, -1):
        alist[0], alist[i] = alist[i], alist[0]
        max_heapify(alist, index=0, size=i)
 
def parent(i):
    return (i - 1)//2
 
def left(i):
    return 2*i + 1
 
def right(i):
    return 2*i + 2
 
def build_max_heap(alist): 
    length = len(alist)
    start = parent(length - 1)
    while start >= 0:
        max_heapify(alist, index=start, size=length)
        start = start - 1
 
def max_heapify(alist, index, size):
    l = left(index)
    r = right(index)
    if (l < size and alist[l] > alist[index]):
        largest = l
    else:
        largest = index
    if (r < size and alist[r] > alist[largest]):
        largest = r
    if (largest != index):
        alist[largest], alist[index] = alist[index], alist[largest]
        max_heapify(alist, largest, size)

k=0
while k<=n-1:
    heap_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an)

[[-217 -209 -204 ...  911  961  962]
 [-241 -206 -205 ...  953  968  980]
 [-249 -198 -128 ...  940  986  993]
 ...
 [-226 -217 -175 ...  943  988 1006]
 [-241 -235 -198 ...  972  973 1005]
 [-216 -197 -116 ...  895  983 1003]]
Wall time: 9.97 ms


In [6]:
%%time
import numpy as np

def quick_sort(data):
    less = []
    pivotList = []
    more = []
    if len(data) <= 1:
        return data
    else:
        pivot = data[0]
        for i in data:
            if i < pivot:
                less.append(i)
            elif i > pivot:
                more.append(i)
            else:
                pivotList.append(i)
        less = quick_sort(less)
        more = quick_sort(more)
        return less + pivotList + more

k=0
while k<=n-1:
    quick_sort(a[k])
    k=k+1

an = np.asarray(a)
print(an)

[[-217 -217 -209 ...  442  531  531]
 [-241 -241 -206 ...  469  481  481]
 [-249 -249 -198 ...  387  388  388]
 ...
 [-226 -226 -217 ...  454  465  465]
 [-241 -241 -235 ...  523  564  564]
 [-216 -216 -197 ...  263  291  291]]
Wall time: 5.98 ms


In [5]:
%%time
import numpy as np

def tournamentSort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2

    for i, v in enumerate(arr):
        tree[index + i] = (i, v)

    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1)
                if tree[i] is not None and tree[i + 1] is not None:
                    if tree[i] < tree[i + 1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                        tree[i // 2] = tree[i] if tree[i] is not None else tree[i + 1]
            index -= n
    
        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

k=0
while k<=n-1:
    tournamentSort(a[k])
    k=k+1

an = np.asarray(a)
print(an)

[[-217 -217 -209 ...  442  531  531]
 [-241 -241 -206 ...  469  481  481]
 [-249 -249 -198 ...  387  388  388]
 ...
 [-226 -226 -217 ...  454  465  465]
 [-241 -241 -235 ...  523  564  564]
 [-216 -216 -197 ...  263  291  291]]
Wall time: 60.8 ms
